/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoEditorRouteImport } from './routes/video-editor'
import { Route as SharedLinksRouteImport } from './routes/shared-links'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as QuickShareRouteImport } from './routes/quick-share'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as OrganizacoesRouteImport } from './routes/organizacoes'
import { Route as MetaDashboardRouteImport } from './routes/meta-dashboard'
import { Route as MetaCreativesRouteImport } from './routes/meta-creatives'
import { Route as MediaToolsRouteImport } from './routes/media-tools'
import { Route as MediaLibraryRouteImport } from './routes/media-library'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ImageEditorRouteImport } from './routes/image-editor'
import { Route as IdpRouteImport } from './routes/idp'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FreepikStudioRouteImport } from './routes/freepik-studio'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as CanvaStudioRouteImport } from './routes/canva-studio'
import { Route as CalendarV2RouteImport } from './routes/calendar-v2'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiTemplatesRouteImport } from './routes/ai-templates'
import { Route as AiManagerRouteImport } from './routes/ai-manager'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AdvancedAiRouteImport } from './routes/advanced-ai'
import { Route as AbTestsRouteImport } from './routes/ab-tests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsMetaAdsRouteImport } from './routes/settings.meta-ads'
import { Route as MetaCreativesCampaignIdRouteImport } from './routes/meta-creatives.$campaignId'
import { Route as ClientTokenRouteImport } from './routes/client.$token'

const VideoEditorRoute = VideoEditorRouteImport.update({
  id: '/video-editor',
  path: '/video-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedLinksRoute = SharedLinksRouteImport.update({
  id: '/shared-links',
  path: '/shared-links',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickShareRoute = QuickShareRouteImport.update({
  id: '/quick-share',
  path: '/quick-share',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesRoute = OrganizacoesRouteImport.update({
  id: '/organizacoes',
  path: '/organizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaDashboardRoute = MetaDashboardRouteImport.update({
  id: '/meta-dashboard',
  path: '/meta-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaCreativesRoute = MetaCreativesRouteImport.update({
  id: '/meta-creatives',
  path: '/meta-creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaToolsRoute = MediaToolsRouteImport.update({
  id: '/media-tools',
  path: '/media-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaLibraryRoute = MediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageEditorRoute = ImageEditorRouteImport.update({
  id: '/image-editor',
  path: '/image-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IdpRoute = IdpRouteImport.update({
  id: '/idp',
  path: '/idp',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FreepikStudioRoute = FreepikStudioRouteImport.update({
  id: '/freepik-studio',
  path: '/freepik-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvaStudioRoute = CanvaStudioRouteImport.update({
  id: '/canva-studio',
  path: '/canva-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarV2Route = CalendarV2RouteImport.update({
  id: '/calendar-v2',
  path: '/calendar-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTemplatesRoute = AiTemplatesRouteImport.update({
  id: '/ai-templates',
  path: '/ai-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AiManagerRoute = AiManagerRouteImport.update({
  id: '/ai-manager',
  path: '/ai-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedAiRoute = AdvancedAiRouteImport.update({
  id: '/advanced-ai',
  path: '/advanced-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AbTestsRoute = AbTestsRouteImport.update({
  id: '/ab-tests',
  path: '/ab-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetaAdsRoute = SettingsMetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => SettingsRoute,
} as any)
const MetaCreativesCampaignIdRoute = MetaCreativesCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => MetaCreativesRoute,
} as any)
const ClientTokenRoute = ClientTokenRouteImport.update({
  id: '/client/$token',
  path: '/client/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ab-tests': typeof AbTestsRoute
  '/advanced-ai': typeof AdvancedAiRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-manager': typeof AiManagerRoute
  '/ai-templates': typeof AiTemplatesRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bulk': typeof BulkRoute
  '/calendar': typeof CalendarRoute
  '/calendar-v2': typeof CalendarV2Route
  '/canva-studio': typeof CanvaStudioRoute
  '/exports': typeof ExportsRoute
  '/freepik-studio': typeof FreepikStudioRoute
  '/history': typeof HistoryRoute
  '/idp': typeof IdpRoute
  '/image-editor': typeof ImageEditorRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/media-library': typeof MediaLibraryRoute
  '/media-tools': typeof MediaToolsRoute
  '/meta-creatives': typeof MetaCreativesRouteWithChildren
  '/meta-dashboard': typeof MetaDashboardRoute
  '/organizacoes': typeof OrganizacoesRoute
  '/posts': typeof PostsRoute
  '/preview': typeof PreviewRoute
  '/quick-share': typeof QuickShareRoute
  '/roles': typeof RolesRoute
  '/rules': typeof RulesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shared-links': typeof SharedLinksRoute
  '/video-editor': typeof VideoEditorRoute
  '/client/$token': typeof ClientTokenRoute
  '/meta-creatives/$campaignId': typeof MetaCreativesCampaignIdRoute
  '/settings/meta-ads': typeof SettingsMetaAdsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ab-tests': typeof AbTestsRoute
  '/advanced-ai': typeof AdvancedAiRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-manager': typeof AiManagerRoute
  '/ai-templates': typeof AiTemplatesRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bulk': typeof BulkRoute
  '/calendar': typeof CalendarRoute
  '/calendar-v2': typeof CalendarV2Route
  '/canva-studio': typeof CanvaStudioRoute
  '/exports': typeof ExportsRoute
  '/freepik-studio': typeof FreepikStudioRoute
  '/history': typeof HistoryRoute
  '/idp': typeof IdpRoute
  '/image-editor': typeof ImageEditorRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/media-library': typeof MediaLibraryRoute
  '/media-tools': typeof MediaToolsRoute
  '/meta-creatives': typeof MetaCreativesRouteWithChildren
  '/meta-dashboard': typeof MetaDashboardRoute
  '/organizacoes': typeof OrganizacoesRoute
  '/posts': typeof PostsRoute
  '/preview': typeof PreviewRoute
  '/quick-share': typeof QuickShareRoute
  '/roles': typeof RolesRoute
  '/rules': typeof RulesRoute
  '/schedule': typeof ScheduleRoute
  '/shared-links': typeof SharedLinksRoute
  '/video-editor': typeof VideoEditorRoute
  '/client/$token': typeof ClientTokenRoute
  '/meta-creatives/$campaignId': typeof MetaCreativesCampaignIdRoute
  '/settings/meta-ads': typeof SettingsMetaAdsRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ab-tests': typeof AbTestsRoute
  '/advanced-ai': typeof AdvancedAiRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-manager': typeof AiManagerRoute
  '/ai-templates': typeof AiTemplatesRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bulk': typeof BulkRoute
  '/calendar': typeof CalendarRoute
  '/calendar-v2': typeof CalendarV2Route
  '/canva-studio': typeof CanvaStudioRoute
  '/exports': typeof ExportsRoute
  '/freepik-studio': typeof FreepikStudioRoute
  '/history': typeof HistoryRoute
  '/idp': typeof IdpRoute
  '/image-editor': typeof ImageEditorRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/media-library': typeof MediaLibraryRoute
  '/media-tools': typeof MediaToolsRoute
  '/meta-creatives': typeof MetaCreativesRouteWithChildren
  '/meta-dashboard': typeof MetaDashboardRoute
  '/organizacoes': typeof OrganizacoesRoute
  '/posts': typeof PostsRoute
  '/preview': typeof PreviewRoute
  '/quick-share': typeof QuickShareRoute
  '/roles': typeof RolesRoute
  '/rules': typeof RulesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shared-links': typeof SharedLinksRoute
  '/video-editor': typeof VideoEditorRoute
  '/client/$token': typeof ClientTokenRoute
  '/meta-creatives/$campaignId': typeof MetaCreativesCampaignIdRoute
  '/settings/meta-ads': typeof SettingsMetaAdsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ab-tests'
    | '/advanced-ai'
    | '/ai-chat'
    | '/ai-manager'
    | '/ai-templates'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/bulk'
    | '/calendar'
    | '/calendar-v2'
    | '/canva-studio'
    | '/exports'
    | '/freepik-studio'
    | '/history'
    | '/idp'
    | '/image-editor'
    | '/inbox'
    | '/integrations'
    | '/media-library'
    | '/media-tools'
    | '/meta-creatives'
    | '/meta-dashboard'
    | '/organizacoes'
    | '/posts'
    | '/preview'
    | '/quick-share'
    | '/roles'
    | '/rules'
    | '/schedule'
    | '/settings'
    | '/shared-links'
    | '/video-editor'
    | '/client/$token'
    | '/meta-creatives/$campaignId'
    | '/settings/meta-ads'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ab-tests'
    | '/advanced-ai'
    | '/ai-chat'
    | '/ai-manager'
    | '/ai-templates'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/bulk'
    | '/calendar'
    | '/calendar-v2'
    | '/canva-studio'
    | '/exports'
    | '/freepik-studio'
    | '/history'
    | '/idp'
    | '/image-editor'
    | '/inbox'
    | '/integrations'
    | '/media-library'
    | '/media-tools'
    | '/meta-creatives'
    | '/meta-dashboard'
    | '/organizacoes'
    | '/posts'
    | '/preview'
    | '/quick-share'
    | '/roles'
    | '/rules'
    | '/schedule'
    | '/shared-links'
    | '/video-editor'
    | '/client/$token'
    | '/meta-creatives/$campaignId'
    | '/settings/meta-ads'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ab-tests'
    | '/advanced-ai'
    | '/ai-chat'
    | '/ai-manager'
    | '/ai-templates'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/bulk'
    | '/calendar'
    | '/calendar-v2'
    | '/canva-studio'
    | '/exports'
    | '/freepik-studio'
    | '/history'
    | '/idp'
    | '/image-editor'
    | '/inbox'
    | '/integrations'
    | '/media-library'
    | '/media-tools'
    | '/meta-creatives'
    | '/meta-dashboard'
    | '/organizacoes'
    | '/posts'
    | '/preview'
    | '/quick-share'
    | '/roles'
    | '/rules'
    | '/schedule'
    | '/settings'
    | '/shared-links'
    | '/video-editor'
    | '/client/$token'
    | '/meta-creatives/$campaignId'
    | '/settings/meta-ads'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbTestsRoute: typeof AbTestsRoute
  AdvancedAiRoute: typeof AdvancedAiRoute
  AiChatRoute: typeof AiChatRoute
  AiManagerRoute: typeof AiManagerRoute
  AiTemplatesRoute: typeof AiTemplatesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BulkRoute: typeof BulkRoute
  CalendarRoute: typeof CalendarRoute
  CalendarV2Route: typeof CalendarV2Route
  CanvaStudioRoute: typeof CanvaStudioRoute
  ExportsRoute: typeof ExportsRoute
  FreepikStudioRoute: typeof FreepikStudioRoute
  HistoryRoute: typeof HistoryRoute
  IdpRoute: typeof IdpRoute
  ImageEditorRoute: typeof ImageEditorRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MediaLibraryRoute: typeof MediaLibraryRoute
  MediaToolsRoute: typeof MediaToolsRoute
  MetaCreativesRoute: typeof MetaCreativesRouteWithChildren
  MetaDashboardRoute: typeof MetaDashboardRoute
  OrganizacoesRoute: typeof OrganizacoesRoute
  PostsRoute: typeof PostsRoute
  PreviewRoute: typeof PreviewRoute
  QuickShareRoute: typeof QuickShareRoute
  RolesRoute: typeof RolesRoute
  RulesRoute: typeof RulesRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SharedLinksRoute: typeof SharedLinksRoute
  VideoEditorRoute: typeof VideoEditorRoute
  ClientTokenRoute: typeof ClientTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-editor': {
      id: '/video-editor'
      path: '/video-editor'
      fullPath: '/video-editor'
      preLoaderRoute: typeof VideoEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-links': {
      id: '/shared-links'
      path: '/shared-links'
      fullPath: '/shared-links'
      preLoaderRoute: typeof SharedLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-share': {
      id: '/quick-share'
      path: '/quick-share'
      fullPath: '/quick-share'
      preLoaderRoute: typeof QuickShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes': {
      id: '/organizacoes'
      path: '/organizacoes'
      fullPath: '/organizacoes'
      preLoaderRoute: typeof OrganizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-dashboard': {
      id: '/meta-dashboard'
      path: '/meta-dashboard'
      fullPath: '/meta-dashboard'
      preLoaderRoute: typeof MetaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-creatives': {
      id: '/meta-creatives'
      path: '/meta-creatives'
      fullPath: '/meta-creatives'
      preLoaderRoute: typeof MetaCreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-tools': {
      id: '/media-tools'
      path: '/media-tools'
      fullPath: '/media-tools'
      preLoaderRoute: typeof MediaToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-library': {
      id: '/media-library'
      path: '/media-library'
      fullPath: '/media-library'
      preLoaderRoute: typeof MediaLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-editor': {
      id: '/image-editor'
      path: '/image-editor'
      fullPath: '/image-editor'
      preLoaderRoute: typeof ImageEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idp': {
      id: '/idp'
      path: '/idp'
      fullPath: '/idp'
      preLoaderRoute: typeof IdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freepik-studio': {
      id: '/freepik-studio'
      path: '/freepik-studio'
      fullPath: '/freepik-studio'
      preLoaderRoute: typeof FreepikStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canva-studio': {
      id: '/canva-studio'
      path: '/canva-studio'
      fullPath: '/canva-studio'
      preLoaderRoute: typeof CanvaStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar-v2': {
      id: '/calendar-v2'
      path: '/calendar-v2'
      fullPath: '/calendar-v2'
      preLoaderRoute: typeof CalendarV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-templates': {
      id: '/ai-templates'
      path: '/ai-templates'
      fullPath: '/ai-templates'
      preLoaderRoute: typeof AiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-manager': {
      id: '/ai-manager'
      path: '/ai-manager'
      fullPath: '/ai-manager'
      preLoaderRoute: typeof AiManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-ai': {
      id: '/advanced-ai'
      path: '/advanced-ai'
      fullPath: '/advanced-ai'
      preLoaderRoute: typeof AdvancedAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ab-tests': {
      id: '/ab-tests'
      path: '/ab-tests'
      fullPath: '/ab-tests'
      preLoaderRoute: typeof AbTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/meta-ads': {
      id: '/settings/meta-ads'
      path: '/meta-ads'
      fullPath: '/settings/meta-ads'
      preLoaderRoute: typeof SettingsMetaAdsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/meta-creatives/$campaignId': {
      id: '/meta-creatives/$campaignId'
      path: '/$campaignId'
      fullPath: '/meta-creatives/$campaignId'
      preLoaderRoute: typeof MetaCreativesCampaignIdRouteImport
      parentRoute: typeof MetaCreativesRoute
    }
    '/client/$token': {
      id: '/client/$token'
      path: '/client/$token'
      fullPath: '/client/$token'
      preLoaderRoute: typeof ClientTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MetaCreativesRouteChildren {
  MetaCreativesCampaignIdRoute: typeof MetaCreativesCampaignIdRoute
}

const MetaCreativesRouteChildren: MetaCreativesRouteChildren = {
  MetaCreativesCampaignIdRoute: MetaCreativesCampaignIdRoute,
}

const MetaCreativesRouteWithChildren = MetaCreativesRoute._addFileChildren(
  MetaCreativesRouteChildren,
)

interface SettingsRouteChildren {
  SettingsMetaAdsRoute: typeof SettingsMetaAdsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMetaAdsRoute: SettingsMetaAdsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbTestsRoute: AbTestsRoute,
  AdvancedAiRoute: AdvancedAiRoute,
  AiChatRoute: AiChatRoute,
  AiManagerRoute: AiManagerRoute,
  AiTemplatesRoute: AiTemplatesRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BulkRoute: BulkRoute,
  CalendarRoute: CalendarRoute,
  CalendarV2Route: CalendarV2Route,
  CanvaStudioRoute: CanvaStudioRoute,
  ExportsRoute: ExportsRoute,
  FreepikStudioRoute: FreepikStudioRoute,
  HistoryRoute: HistoryRoute,
  IdpRoute: IdpRoute,
  ImageEditorRoute: ImageEditorRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  MediaLibraryRoute: MediaLibraryRoute,
  MediaToolsRoute: MediaToolsRoute,
  MetaCreativesRoute: MetaCreativesRouteWithChildren,
  MetaDashboardRoute: MetaDashboardRoute,
  OrganizacoesRoute: OrganizacoesRoute,
  PostsRoute: PostsRoute,
  PreviewRoute: PreviewRoute,
  QuickShareRoute: QuickShareRoute,
  RolesRoute: RolesRoute,
  RulesRoute: RulesRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SharedLinksRoute: SharedLinksRoute,
  VideoEditorRoute: VideoEditorRoute,
  ClientTokenRoute: ClientTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
